### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by kulothunganug** [maltfield/cross-platform-python-gui#10]
**Describe the bug**
I am using this repo to build my app.
In my app I use some `json` files to work with
ex:-
```py
with open('screens.json') as f:
    ...
```
but after building the app using this repo, I got file not found error.
So please tell me a proper way to work with paths when using this repo to build my app

**Comment by maltfield** [comment]
Non-code assets need to be added to `datas` as described in issue #6 

Please be aware that the contents of your app is "frozen" and will be read-only. If you want to write contents to that json during runtime, you're going to need to put it on the fs somewhere -- for this you can create a directory in something like

```
os.path.join( os.path.expanduser('~') )
```

For an example of how this is done with a downstream example, see:

 * https://github.com/BusKill/buskill-app/blob/30681107fbcb82d5f4e6252c173953c8a6dbdeea/src/packages/buskill/__init__.py#L480

To get the absolute path to where your cross-platform executable lives, use `sys.path[0]`. See how I do this with `APP_DIR` here:

 * https://github.com/BusKill/buskill-app/blob/30681107fbcb82d5f4e6252c173953c8a6dbdeea/src/packages/buskill/__init__.py#L48

Depending on where you want your files to live, you may have to play around to see how it behaves on all three platforms:

 * https://github.com/BusKill/buskill-app/blob/30681107fbcb82d5f4e6252c173953c8a6dbdeea/src/packages/buskill/__init__.py#L228-L322

**Comment by maltfield** [comment]
Hope this helps
