### ISSUE TITLE
Remove a buggy tag

### ISSUE THREAD

**Issue by darpan5552** [maltfield/cross-platform-python-gui#7]
**Describe the bug**
You have a tag which is causing conflict while pushing to github

**To Reproduce**
+ I forked and cloned your repository. 
+ Added my own code to it and committed
+ When pushing to github i got  ```dst refspec refs/heads/master matches more than one```

**How i solved it?**
There was tag created in june 2020, named ```refs/heads/master``` which was causing this problem.
After doing ```git tag -d refs/heads/master```, everything is fine now.

**Comment by maltfield** [comment]
interesting. Thanks for the report.

Can you please post the exact command and output starting with the `git clone` and ending with the error?

**Comment by darpan5552** [comment]
@maltfield 
I mailed you a video of this bug and also the method used to solve it on your registered mail with github.
If you follow it on this repo then anyone forking this repo will not face problems.

**Comment by maltfield** [comment]
@darpan5552 Unfortunately, `michael@michaelaltfied.net` is intentionally an autoreply service only that should send you instructions on how to get my current email address (spam prevention). It just drops/ignores emails above some byte size, which may have happened to your email if it had a video attachment. Spoiler, you can get my current email address here:

 * https://email.michaelaltfield.net

Anyway, it would be best if you could upload it to github or youtube or something and link it directly in this ticket.

**Comment by maltfield** [comment]
Just for my reference, this tag `refs/heads/master` (full refspec = `refs/tags/refs/heads/master`) points to commit `5c3a835deceb2d50ab39606f5e074edc7c49f94c`

 * https://github.com/maltfield/cross-platform-python-gui/commit/5c3a835deceb2d50ab39606f5e074edc7c49f94c

```
user@disp7434:~/sandbox/cross-platform-python-gui$ git rev-list -n1 refs/tags/refs/heads/master
5c3a835deceb2d50ab39606f5e074edc7c49f94c
user@disp7434:~/sandbox/cross-platform-python-gui$ 
```

**Comment by maltfield** [comment]
I was not able to reproduce this bug. I created a new fork, and I was able to commit & push, which successfully triggered GitHub Actions (there's an unrelated bug with MacOS builds, which I've fixed and will merge into this repo shortly).

 * https://github.com/OpenSourceEcology/cross-platform-python-gui/commit/6e518585a7940371081bbdaff75ccd94e88f7c03
 * https://github.com/OpenSourceEcology/cross-platform-python-gui/actions/runs/523295047

@darpan5552 what version of git are you using? And what OS?

Anyway, I couldn't figure out why I had created this tag. My best-guess is that I created it accidentally when trying to get OS-specific GitHub releases working back in June 2020. So I tried deleting the tag.

```
user@buskill:~/sandbox/cross-platform-python-gui$ git push --delete origin refs/tags/refs/heads/master
To github.com:maltfield/cross-platform-python-gui.git
 - [deleted]         refs/heads/master
user@buskill:~/sandbox/cross-platform-python-gui$
```

Please try again and let me know if this issue is fixed for you.

**Comment by darpan5552** [comment]
Here i compressed the old video file and also provided the solution.
https://user-images.githubusercontent.com/57829384/106372173-1e9ed480-6393-11eb-84a2-deb168130d9e.mp4

Reason why you are unable to reproduce the error because you are not on master branch. `refs/heads/master` only clashes with master branch, not with others.
I will fork your repo again and see if error still persists.

**Comment by darpan5552** [comment]
@maltfield 
Issue Solved :+1:

**Comment by maltfield** [comment]
thanks.

> Reason why you are unable to reproduce the error because you are not on master branch

fwiw, I was on the `master` branch. After watching the video, I can see that the reason I didn't encounter the issue was because I was executing this command:

```
git push
```

and you were executing this command:

```
git push origin master
```

**Comment by darpan5552** [comment]
@maltfield 
Are you on discord or any similar app?
Level of privacy on your email is much more to talk there.
